version: '2'
services:
  ngnix:
    image: nginx:1.11.10-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
  web:
    build: .
    volumes:
      - .:/app
    links:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: todos
      DB_USERNAME: todoapp
      DB_PASSWORD: ''
      TEST_DB_NAME: todos_testing
    cached: true
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
