version: '2'
services:
  ngnix:
    image: nginx:1.11.10-alpine
    ports:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
  web:
    build: .
    volumes:
      - .:/app
    links:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
