version: '2'
services:
  ngnix:
    image: nginx:1.11.10-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
  web:
    build: .
    ports:
      - "9000"
    volumes:
      - .:/app
    links:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: todos
      DB_USERNAME: todoapp
      DB_PASSWORD: ''
  postgres:
    image: postgres:9.6.2-alpine
    volumes:
      - ./bin/create-db:/docker-entrypoint-initdb.d/create-db
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
      TEST_DB_NAME: todos_testing
